version: 2  
updates:  
  - package-ecosystem: "pip"  # Usa pip para gerenciar dependências  
    directory: "/"              # Diretório do projeto  
    schedule:  
      interval: "weekly"        # Atualiza semanalmente  
    commit-message:  
      prefix: "fix"             # Prefixo da mensagem de commit  
    
  - package-ecosystem: "jupyter" # Para Jupyter Notebooks  
    directory: "/"               # Diretório do projeto  
    schedule:  
      interval: "weekly"         # Atualiza semanalmente  
    commit-message:  
      prefix: "fix"   
