version: 2  
updates:  
  # Configuração para dependências de Python (requirements.txt)  
  - package-ecosystem: "pip"  
    directory: "/"  # Diretório onde está o requirements.txt  
    schedule:  
      interval: "daily"  # Verificações diárias  
    commit-message:  
      prefix: "fix"  # Prefixo na mensagem de commit  
      include: "scope"  # Inclui o nome da dependência na mensagem  

  # Configuração para dependências de JavaScript (package.json)  
  - package-ecosystem: "npm"  
    directory: "/"  # Diretório onde está o package.json  
    schedule:  
      interval: "weekly"  # Verificações semanais  
    commit-message:  
      prefix: "fix"  # Prefixo na mensagem de commit  
      include: "scope"  # Inclui o nome da dependência na mensagem  
    versioning-strategy: "auto"  # Estratégia de versão
