# Full Version Dependant

version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/updater"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      aws-sdk:
        patterns:
          - "aws-sdk-*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
          
  # Watch the per-ecosystem native helpers
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v1"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v2"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "docker"
    directory: "/go_modules"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "gomod"
    directory: "/go_modules/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "mix"
    directory: "/hex/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"


      

      
      

      


      

      
      
