version: 2
updates:
  - package-ecosystem: "npm" # Altere para o gerenciador de pacotes que você está usando
    directory: "/" # O diretório onde está o arquivo de dependências
    schedule:
      interval: "daily" # A frequência das atualizações
    open-pull-requests-limit: 10 # O número máximo de pull requests abertos

